# Site wide configuration

title: Eugeniu Cararus
locale: en_US
description: Static blog about couputers and software.
logo: site-logo.png
search: true
url: #https://ecararus.github.io/

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Site owner
owner:
  name: Eugeniu Cararus
  avatar: bio-photo.jpg
  email: cararuseugeniu@gmail.com
  disqus-shortname:
  twitter: eugeniu_c
  github: ecararus
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: cararuseugeniu
  google:
    plus: 110827631098363888935
    analytics: UA-73759976-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
